version: '3' # specify docker-compose version

services:
  database:
    build: ./db
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db_data:/var/lib/postgresql/data
      - .:/express-backend

  express: #name of the second service
    build: . # specify the directory of the Dockerfile
    volumes:
      - .:/express-backend/:rw
      - express_webmodule:/express-backend/node_modules
    ports:
      - "9999:3012" #specify ports forewarding 3012 is default in .env file
    restart: always
    links: 
      - database
    depends_on:
      - database
    environment:
      WAIT_HOSTS: ${DB_HOST}:${DB_PORT}
   
volumes:
  express_webmodule:
  db_data:
